run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unused

linters-settings:
  revive:
    rules:
      - name: var-naming
      - name: exported
      - name: package-comments
      - name: indent-error-flow
